

#' Apply any function to a cursor region 
#' 
#' This function is almost never used directly. 
#' See [add_cursor_point] and friends on how to use more specific variants. 
#'
#' @param ephysdata a tibble with ephys data  
#'
#' @param name the name of the cursor
#' @param cfun a cursor-type function, see \link{cursors}
#' @param fun,model_fun function that is used by the cursor to calculate its results
#' @param annot defines how the cursor is shown in \link{ggsweeps}. 
#' @param ... aditional parameters passed to cfun
#' @param start start value
#' @param end end value
#' @param condition optional: a logical expression evaluated in the context of the input data. Only for rows where the expression evaluates to TRUE the cursor will be calculated.  
#' @param stream optional: select stream for the cursor to operate on. See add_stream. 
#' @param auto_hoist a list of the form list(resultname = "x") specifying cursor results to be hoisted
#' @param .transform a list of the form list(resultname = fun) specifying how cursor results are to be transformed. Defaults to use the defaults of the cfun.  
#' @param filter optional: a function that modifies the data 
#'
#' @export
add_cursor<- function(ephysdata, name, start, end, cfun, stream,  condition=TRUE, annot=attr(cfun, "annot") , annot_under=NULL, 
                      auto_hoist=tibble::lst(!!name:="y"), .transform=tibble::lst(!!name:=auto_transform), 
                      filter_fun=unfiltered, filter_fun2=unfiltered, ...){

  assertthat::assert_that(
    !missing(start), !missing(end), 
    msg=glue::glue("error in add_cursor(name= {name}... : please provide start and end values for the cursor "))
  
  
  assertthat::assert_that(
    "ptrs" %in% names(ephysdata), 
    msg="adding cursors require a sepecial column named 'ptrs' in your data set, which is missing"
    )
  
  name2=paste0(name, ".csr")
  
  
  
  if(missing(stream)){
    if(! "data" %in% names(ephysdata)){
      #cli::cli_abort("please add a stream before using cursors")
      ephysdata <- ephysdata %>% ungroup %>% add_stream()
    }
    ephysdata<-ephysdata %>%
      rowwise %>%
      mutate(  !!name2  := list(
        cfun(
          # get_defaultsstream uses cut_df and downsample_df, and applies yoffset.
          get_defaultstream(data , yoffset, {{start}}, {{end}}, filter_fun=filter_fun, filter_fun2=filter_fun2),
          start={{start}},
          end={{end}}, 
          condition={{condition}},
          annot=annot,
          ...) ),
        .after=id
      )
    
  }else{
    ephysdata<-ephysdata %>%
      rowwise %>% 
      mutate(  !!name2  := list( 
        cfun(
          # fixme: if we use a stream generated by stream_, we do not handle it the same way. 
          {{stream}} %>% filter(x %>% between({{start}}, {{end}})), 
          start={{start}}, 
          end={{end}}, 
          condition={{condition}},
          annot=annot,
          ...) ),
        .after=id
      )
  }
  
  attr(ephysdata[[name2]], "annot") <- annot
  attr(ephysdata[[name2]], "annot_under") <- annot_under
  ephysdata %>% tidyr::hoist(name2, !!!auto_hoist, .remove = F, .transform = .transform) %>% ungroup
}








#' add a bar
#' 
#' @export
add_cursor_bar<-function(ephysdata, name, start, end,  ...){
  add_cursor(ephysdata, name=name, start=start, end=end, cfun= bar_,  ...)
}

#' point cursor, fast version
#' 
#' (not tested if in ephys4 (this package), it is still faster then the standard add_cursor_point). 
#' included here for packwards compatibility and maybe later performance benchmarking. 
#' 
#' point cursor, fast version (expects a stream called 'data' and does no filtering on its own, fast because no rowwise)
#' @inheritParams add_cursor
#' @export
add_cursor_point_fast<-function(df, name, start, end, fun, annot=NA){
  # this code will work for all cases were our fun just returns "y". 
  # we still need to find a solution were for funs were we calculate more than this, like AP, and models. 
  
      # f=function(x)data.frame(model=x[1], st=0, en=3);mtcars %>% group_by(cyl) %>% summarise(f(cyl))
  
  # we also need to check again if the left_join(df,df %>%...) pattern is applied correctly here (see performance tests.Rmd for rationale and example of the pattern.)
  name=paste0(name, ".csr")
  left_join(df, df %>% tidyr::unnest(data) %>% group_by(id) %>%  
              summarise(y_=fun(y[x %>% between(start,end)]), x=x[x %>% between(start,end)][which.min(abs(y[x %>% between(start,end)]-y_))[1]], st=start, en=end), by="id") %>% 
    rename(y=y_) %>%
    tidyr::nest({{name}}:=c(x,y,st,en))-> df
  
  if(!missing(annot))   attr(df[[name]], "annot") <- annot
  df
}


#' Find single point in cursor region
#' 
#' @inheritParams add_cursor
#' @export
#' @examples 
#' ephysdata::examplefile("OO_GABA") %>% read_ROBOO() %>% head(1) %>%   
#'add_cursor_point(name = "peak",  39, 119, fun = min) %>% 
#'  ggsweeps() + 
#'  ggtitle("Using add_cursor_point(..., fun=min) to find a minimum")
add_cursor_point<-function(ephysdata, name, start, end,  fun, stream, condition=TRUE,  filter_fun=unfiltered, filter_fun2=unfiltered, 
                           annot=annot_range_point(), ...){
  add_cursor(ephysdata, name=name, start={{start}}, end={{end}},  fun=fun, stream=stream, cfun= point_,  filter_fun={{filter_fun}}, filter_fun2={{filter_fun2}},annot=annot, condition={{condition}}, ...)
}

#' Find multiple points in cursor region
#' 
#' points cursor (multiple!). Calls \code{\link{peaks_multy_}} to cut its region into segments using a threshold function, 
#' and to apply the function \code{fun} to the segments above or below this threshold. This typically yields multiple results per cursor, 
#' which can be conveniently further processed by another cursor when the long format is used. A typical example is the AP cursor.  
#' 
#' @param long add_cursor_points: output cursor results in long format (not compatible with ggsweeps() currently). 
#' @param direction add_cursor_points: apply fun to segments above or below threshold 
#' @inheritParams add_cursor

#' @export
#' @examples 
#' read_PATCHMASTER(examplefile("cardiopatch/21-07-Cardio.dat"), exp=23, ser=3,  trc="Vmon") %>% 
#'  add_cursor_points("starts", 10, 30, fun=max, direction = "above") -> points 
#'  
#'  # plot:
#'  points %>%
#'  ggsweeps(maxpoints = 1e12)
#'  
#'  # how to get the point coordinates:
#'  points %>% tidyr::unnest_wider(starts.csr) %>% tidyr::unnest_longer(c(x,y))
add_cursor_points<-function(ephysdata, name, start=0, end=NA,  fun, long=FALSE, direction=c("above", "below"), ...){
  ephysdata <- add_cursor(ephysdata, name=name, start=start, end=end, fun=fun, cfun= peaks_multy_, direction=direction, ...)
  if(long){
    csrname=paste0(name, ".csr")
    xname=paste0(name, ".x")
    yname=paste0(name, ".y")
      ephysdata %>% 
      tidyr::hoist(
        !!csrname,
        !!xname:="x",
        !!yname:="y", .remove = FALSE) %>%
          tidyr::unnest(cols = c(!!xname, !!yname)) #%>% select(-csrname)
  }else{
    ephysdata
  }
    
    
    
}



#' find a level in cursor region
#' 
#' The typical use case is to find  the baseline level of a measurement. 
#' 
#' @inheritParams add_cursor
#' @export
#' @examples 
#' ephysdata::examplefile("OO_GABA") %>% read_ROBOO() %>% head(1) %>%   
#'add_cursor_level(name = "baseline",  0, 30, fun = mean) %>% 
#'  ggsweeps() + 
#'  ggtitle("Using add_cursor_level(..., fun=mean) to find a baseline level")
add_cursor_level<-function(ephysdata, name, start, end,  fun, ...){
  add_cursor(ephysdata, name=name, start=start, end=end,fun=fun, cfun= level_, ...)
}


#' Fit any model to cursor region 
#' 
#' with this cursor, any model can be fitted to the cursor region. 
#' For the special case of exponential models, it is recommended to use \code{\link{add_cursor_expfit}}
#' 
#' @export
#' @seealso [add_cursor], [add_cursor_expfit]
#' @inheritParams add_cursor
#' @param x0 location parameter that shifts the curve along the x-axis and defines the reference point where the model is anchored. 
#' @examples 
#' read_PATCHMASTER(ephysdata::examplefile("NaV"), ser=2) %>% tail(1) %>% 
#'  add_cursor_model("fit_from_c1", 0.011, 0.019, x0=0.011, model_fun_exp,  st2=0.01, en2=0.03) %>% 
#'  add_cursor_model("fit_from_0_", 0.011, 0.019,          model_fun_exp,  st2=0.01, en2=0.03) %>% 
#'  select(starts_with("fit"),-ends_with(".csr")) %>% 
#'  tidyr::unnest_wider(starts_with("fit"), names_sep = ".") 
add_cursor_model<-function(ephysdata, name, start, end,  model_fun, x0=0,...){
 add_cursor(ephysdata, name=name, start=start, end=end, model_fun=model_fun, x0=x0,cfun= model_, auto_hoist=tibble::lst(!!name:="model"), .transform= tibble::lst(!!name:=function(x){coef(x[[1]])}),...)
}


#' Fit exponential decay
#'
#' @inheritParams add_cursor
#' @param x0 location parameter that shifts the curve along the x-axis and defines the reference point where the model is anchored. 
#' x0 is automatically set to the left cursor by default
#' @export
#' @seealso [add_cursor], [add_cursor_expfit]
#' @examples 
#' read_PATCHMASTER(ephysdata::examplefile("NaV"), ser=2) %>% tail(1) %>% 
#'  add_cursor_expfit("fit", 0.011, 0.019, st2=0.01, en2=0.03) -> fitted
#'  
#'  # plot the result:
#'  fitted %>% ggsweeps()
#'  
#'  # show all fit results: 
#'  fitted %>% select(fit) %>% 
#'  tidyr::unnest_wider(fit, names_sep = ".") 
add_cursor_expfit<-function(ephysdata, name, start, end, x0=start,...){
  add_cursor(ephysdata, name=name, start=start, end=end, model_fun=model_fun_exp, x0=x0,cfun= model_, 
             auto_hoist=tibble::lst(!!name:="model"), 
             .transform= tibble::lst(!!name:=function(x){
               coefs=coef(x[[1]])
               coefs["tau"]<-1/exp(coefs["log_alpha"])
               coefs
               }),...)
}


auto_transform <- function(x){ if(!is.null(attr(x, ".transform"))) attr(x,".transform")(x) else x }  # get transform by attribute
